name: Secure Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print a Secret
        env:
          API_KEY: ${{ secrets.API_KEY }}  # تخزين الـ Secret في متغير بيئي
        run: |
          echo "The API key is: $API_KEY"
