name: Secure Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Secret
        run: echo "Your API Key is ${{ secrets.API_KEY }}"
